name: 'Terraform run'
description: 'Action to generate terraform runs'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  tf_api_token:
    description: 'Terraform token'
    required: true
runs:
  using: "composite"
  steps:             
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ inputs.tf_api_token }}
        terraform_version: '1.7.3'

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive -diff
      shell: bash
      working-directory: ./dev

    - name: Post Format Comment
      if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.fmt.outcome == 'success' || steps.fmt.outcome == 'failure') }}
      uses: GetTerminus/terraform-pr-commenter@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commenter_type: fmt
        commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
        commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}

    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash
      working-directory: ./dev
    
    - name: Post Init Comment
      if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.init.outcome == 'success' || steps.init.outcome == 'failure') }}
      uses: GetTerminus/terraform-pr-commenter@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commenter_type: init
        commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
        commenter_exitcode: ${{ steps.init.outputs.exitcode }}
    
    - name: Terraform get workspace
      id: shows
      run: echo "TF_WORKSPACE=$(terraform workspace show)" >> $GITHUB_ENV
      shell: bash
      working-directory: ./dev

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash
      working-directory: ./dev

    - name: Post TF Validate Comment
      if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure') }}
      uses: GetTerminus/terraform-pr-commenter@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commenter_type: validate
        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -out=workspace.plan |& tee tf_plan.txt
      shell: bash
      working-directory: ./dev
    
    - name: Post TF Plan Comment
      uses: GetTerminus/terraform-pr-commenter@v3.0.3
      if: ${{ !cancelled() && github.event_name == 'pull_request' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure') }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        commenter_type: plan
        commenter_plan_path: tf_plan.txt
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
    
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply workspace.plan
      shell: bash
      working-directory: ./dev