name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    workflow_dispatch:
        inputs:
            environment:
                required: true
                default: dev
                type: choice
                options:
                    - dev
                    - prod

jobs:
  Explore-GitHub-Actions:
    environment: ${{ inputs.environment }}
    runs-on:  ${{ inputs.environment == 'prod' && 'prod-runner' || 'dev-runner' }}
    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false
        #     token: ${{ secrets.CUSTOM_TOKEN }}

      - name: test
        run: |
            echo "${{github.sha}}" > foo.txt
            git remote set-url origin "https://${{ secrets.CUSTOM_TOKEN }}@github.com/${{ github.repository }}.git"
            git config user.name "github-actions[bot]"
            git config user.email "test@test.com"
            git add foo.txt
            git commit -m "foo test commit"
            git push origin "${{github.ref}}"
