name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test
        env:
            CUSTOM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "${{github.sha}}" > foo.txt
            git config user.name "github-actions[bot]"
            git config user.email "test@test.com"
            git config user.password ""invalid_password"
            git add foo.txt
            git commit -m "foo test commit"
            git push origin "${{ github.ref }}"
